### ISSUE TITLE
Create new ecj.jar for ant compile tasks

### ISSUE THREAD

**Issue by itaygr** [maxeler/eclipse#5]
in ant:

``` xml
<taskdef name="maxjcompiler" classname="org.eclipse.jdt.core.ant.taskdef.MaxjTask" classpath="${env.MAXCOMPILERDIR}/lib/MaxIDE/ecj.jar" onerror="ignore"/>
```

is using an old version of the compiler. We need a release for ecj as well.

**Comment by kulesc** [comment]
I think we can close this issue now since we have a new release which includes ecj.jar.
